replicaCount: 1

image:
  repository: azureks.azurecr.io/api-gateway/gateway
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: "gateway"
fullnameOverride: "gateway"

probes:
  endpoints:
    liveness: "/api/health/alive"
    readiness: "/api/health/ready"
  initialDelay: 5
  interval: 10
  timeout: 120

serviceAccount:
  create: true
  name: "gateway"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  name: "gateway"

ingress:
  enabled: false
  
resources:
  limits:
    cpu: 50m
    memory: 250Mi
  requests:
    cpu: 25m
    memory: 175Mi
    
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 90