apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "34"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"33"},"creationTimestamp":"2022-05-29T20:46:36Z","generation":82,"labels":{"app":"mongo"},"name":"mongo","namespace":"default","resourceVersion":"127881903","uid":"cb81b16a-407e-44c8-b747-3da8caea2182"},"spec":{"progressDeadlineSeconds":600,"replicas":0,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"mongo"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2022-11-18T22:21:09-07:00"},"creationTimestamp":null,"labels":{"app":"mongo"}},"spec":{"containers":[{"args":["--dbpath","/data/db"],"image":"mongo:6","imagePullPolicy":"Always","name":"mongo","resources":{"limits":{"cpu":"800m","memory":"3Gi"},"requests":{"cpu":"650m","memory":"2Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data/db","name":"mongo-data-dir"},{"mountPath":"/var/secrets/key","name":"keyfile-volume"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"mongo-data-dir","persistentVolumeClaim":{"claimName":"mongo-disk"}},{"name":"keyfile-volume","secret":{"defaultMode":420,"secretName":"keyfile"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2022-05-29T20:46:36Z","lastUpdateTime":"2022-11-19T19:42:39Z","message":"ReplicaSet \"mongo-65985cc447\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2022-11-19T22:17:38Z","lastUpdateTime":"2022-11-19T22:17:38Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":82,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2022-05-29T20:46:36Z"
  generation: 83
  labels:
    app: mongo
  name: mongo
  namespace: default
  resourceVersion: "127886966"
  uid: cb81b16a-407e-44c8-b747-3da8caea2182
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-11-18T22:21:09-07:00"
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      containers:
      - args:
        - --dbpath
        - /data/db
        image: mongo:6
        imagePullPolicy: Always
        name: mongo
        resources:
          limits:
            cpu: 800m
            memory: 3Gi
          requests:
            cpu: 650m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data-dir
        - mountPath: /var/secrets/key
          name: keyfile-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mongo-data-dir
        persistentVolumeClaim:
          claimName: mongo-disk
      - name: keyfile-volume
        secret:
          defaultMode: 420
          secretName: keyfile
status:
  conditions:
  - lastTransitionTime: "2022-11-19T22:17:38Z"
    lastUpdateTime: "2022-11-19T22:17:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-05-29T20:46:36Z"
    lastUpdateTime: "2022-11-19T22:33:32Z"
    message: ReplicaSet "mongo-5db7bf57d4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 83
